name: stepsphere
description: StepSphere - Track your walks, mark your territory, challenge your friends.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Firebase
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.4.3
  firebase_storage: ^12.3.3

  # State Management
  provider: ^6.1.2

  # Maps & Location
  google_maps_flutter: ^2.9.0
  geolocator: ^13.0.1
  geocoding: ^3.0.0

  # Sensors
  pedometer: ^4.0.1
  sensors_plus: ^4.0.2

  # UI
  fl_chart: ^0.69.0
  cached_network_image: ^3.4.1
  flutter_svg: ^2.0.10+1
  shimmer: ^3.0.0
  lottie: ^3.1.2
  cupertino_icons: ^1.0.8

  # Utils
  intl: ^0.19.0
  uuid: ^4.5.1
  shared_preferences: ^2.3.3
  image_picker: ^1.1.2
  permission_handler: ^11.3.1
  url_launcher: ^6.3.1
  share_plus: ^10.1.2
  path_provider: ^2.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/animations/
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
